name: Go Tests
on: [push, pull_request]
jobs:
  build-1_16:
    name: Build 1.16
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - name: Show version
        run: go version
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build
        run: go build -v .

  build-1_17:
    name: Build 1.17
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go
      - name: Show version
        run: go version
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build
        run: go build -v .

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go
      - name: Show version
        run: go version
      - name: Check out code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v ./...
