name: Linters-Main
on:
  push:
    branches:
      - main
jobs:
  golangci-lint:
    name: golangci-lint-latest
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: latest
          args: -c .golangci.yml -v
