name: Linters
on: [push, pull_request]
jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
          args: -c .golangci.yml -v

  markdown-lint:
    name: markdown-lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Markdown files linting
      uses: avto-dev/markdown-lint@v1
      with:
        args: '.'

  terrafmt:
    name: terrafmt
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.17
        id: go
      - name: Show version
        run: go version
      - name: Check out code
        uses: actions/checkout@v2
      - name: Check out terrafmt code
        uses: actions/checkout@v2
        with:
          repository: katbyte/terrafmt
          ref: v0.3.0
          path: terrafmt
      - name: Build terrafmt bin
        run: cd terrafmt && go install ./... && cd ${GITHUB_WORKSPACE}
      - name: Terrafmt diff on html.markdown
        run: find . | egrep "html.markdown" | sort | while read f; do terrafmt diff $f; done >> /tmp/results.html.markdown
      - name: Terrafmt diff on _test.go
        run: find . | egrep "_test.go" | sort | while read f; do terrafmt diff $f; done >> /tmp/results.test.go
      - name: Generate error if results not empty
        run: |
          if [[ -s /tmp/results.html.markdown || -s /tmp/results.test.go ]] ; then 
            cat /tmp/results.html.markdown
            cat /tmp/results.test.go
            echo "terraform blocks in website/test-go files not being properly formatted"
            exit 1
          fi

  tfproviderlint:
    name: tfproviderlint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.17
        id: go
      - name: Show version
        run: go version
      - name: Check out code
        uses: actions/checkout@v2
      - name: Check out tfproviderlint code
        uses: actions/checkout@v2
        with:
          repository: bflad/tfproviderlint
          ref: v0.27.1
          path: tfproviderlint
      - name: Build tfproviderlint bin
        run: cd tfproviderlint && go install ./... && cd ${GITHUB_WORKSPACE}
      - name: Run tfproviderlint
        run: tfproviderlint -AT001=false -AT006=false -R007=false -R009=false -R014=false -R018=false ./...
