name: Markdown Lint
on: [push, pull_request]
jobs:
  md-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Markdown files linting
      uses: avto-dev/markdown-lint@v1
      with:
        args: '.'
